logging:
  level:
    ru.yandex.practicum.filmorate: debug

server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
#    url: jdbc:h2:mem:./db/filmorate
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console.enabled: true


